name: build

on:
  push:
    branches:
      - main

env:
  ECR_REPOSITORY: myapp-rails
  DOCKER_BUILDKIT: 1
  HEAD_SHA: ${{ (github.event_name == 'pull_request' && github.event.pull_request.head.sha) || github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.HEAD_SHA }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ env.HEAD_SHA }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build bundle stage
        uses: docker/build-push-action@v2
        with:
          context: .
          target: bundle
          cache-from: type=local,src=/tmp/.buildx-cache/bundle
          cache-to: type=local,dest=/tmp/.buildx-cache-new/bundle

      - name: Build yarn stage
        uses: docker/build-push-action@v2
        with:
          context: .
          target: yarn
          cache-from: type=local,src=/tmp/.buildx-cache/yarn
          cache-to: type=local,dest=/tmp/.buildx-cache-new/yarn

      - name: Build and Push
        uses: docker/build-push-action@v2
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          context: .
          build-args: |
            SHA=${{ env.HEAD_SHA }}
          tags: |
            ${{ format('{0}/{1}:{2}', steps.login-ecr.outputs.registry, env.ECR_REPOSITORY, env.HEAD_SHA) }}
            ${{ format('{0}/{1}:{2}', steps.login-ecr.outputs.registry, env.ECR_REPOSITORY, 'latest') }}
          push: true
          cache-from: |
            type=local,src=/tmp/.buildx-cache-new/bundle
            type=local,src=/tmp/.buildx-cache-new/yarn
          cache-to: type=inline

      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
