name: e2e

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CHROME_VERSION: "114.0.5735.198-1"

jobs:
  e2e:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database-name:
          - mydb
        database-password:
          - postgres
        database-user:
          - postgres
        database-host:
          - 127.0.0.1
        database-port:
          - 5432
    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ matrix.database-name }}
          POSTGRES_USER: ${{ matrix.database-user }}
          POSTGRES_PASSWORD: ${{ matrix.database-password }}
        options: --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v3

      - name: Set up Ruby, Bundler and Rails
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Chrome
        run: |
          # Add the Google Chrome repository
          wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb \
          && sudo apt install -y --allow-downgrades /tmp/chrome.deb \
          && rm /tmp/chrome.deb

      - name: Set up chrome driver
        uses: nanasess/setup-chromedriver@v2

      - name: Run system specs
        env:
          RAILS_ENV: test
          TEST_DATABASE_URL: postgres://${{ matrix.database-user }}:${{ matrix.database-password }}@${{ matrix.database-host }}:${{ matrix.database-port }}/${{ matrix.database-name }}
        run: |
          bundle exec rails assets:precompile
          bundle exec rails db:test:prepare
          bundle exec rspec spec/system
