version: "3.7"
services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: admin_pass
      POSTGRES_USER: myuser
    expose:
      - "$DB_PORT"
    volumes:
      - ./tmp/backups:/home/backups
    ports:
      - "$DB_PORT:$DB_PORT"
    command: -p $DB_PORT
  redis:
    image: redis:6.0
    restart: always
    command: --port $REDIS_PORT
    volumes:
      - redis-data:/data
    ports:
      - $REDIS_PORT:$REDIS_PORT
    expose:
      - "$REDIS_PORT"
    logging:
      driver: none
  web: &app_base
    build: ./
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec foreman start -f Procfile.dev"
    environment:
      TEST_DATABASE_URL: postgres://myuser:admin_pass@db:$DB_PORT/mydb_test
      DATABASE_URL: postgres://myuser:admin_pass@db:$DB_PORT/mydb
      RAILS_ENV: development
      NODE_ENV: development
      RAILS_MAX_THREADS: 5
      REDIS_HOST: redis
      REDIS_PORT: $REDIS_PORT
      BUNDLE_PATH: /app/vendor/bundle
      BUNDLE_WITHOUT:
    volumes:
      - ./:/app
      - ./vendor/bundle:/app/vendor/bundle
      # exclude volumes
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    ports:
      - "$WEB_PORT:$WEB_PORT"
    depends_on:
      - "db"
      - "redis"
    tty: true
volumes:
  db:
  bundle:
  redis-data:
