# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 7.0'

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem 'sprockets-rails'

# Use postgresql as the database for Active Record
gem 'pg'

# Use Puma as the app server
gem 'puma', '~> 5.0'

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem 'importmap-rails'

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem 'turbo-rails'

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem 'stimulus-rails'

# Use Tailwind CSS [https://github.com/rails/tailwindcss-rails]
gem 'tailwindcss-rails'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'

# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.0'

# Use Active Model has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false

## custom gems
gem 'action_args'
gem 'active_decorator'
gem 'active_hash'
# TODO: replace this with following moduleralized gems to reduce the gem size
# to do that, we need to investigate how to send emails using aws-sdk-ses with devise_invitable
gem 'aws-sdk-rails'
gem 'aws-sdk-s3'
# gem 'aws-sdk-ses'
gem 'cancancan'
gem 'config'
gem 'devise'
gem 'devise_invitable', '~> 2.0.0'
gem 'enum_help'
gem 'html5_validators'
gem 'httparty'
gem 'i18n-tasks'
gem 'inline_svg'
gem 'kaminari'
gem 'lograge'
gem 'lookbook'
gem 'mini_magick'
gem 'net-imap', require: false
gem 'net-pop', require: false
gem 'net-smtp', require: false
gem 'newrelic_rpm'
gem 'nokogiri'
gem 'okcomputer'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'omniauth-rails_csrf_protection'
gem 'rails-flog'
gem 'rexml'
gem 'rubocop', require: false
gem 'rubocop-rails', require: false
gem 'rubocop-rspec', require: false
gem 'sentry-rails'
gem 'sentry-ruby'
gem 'sidekiq', '~> 6.4.2'
gem 'sidekiq-cron'
gem 'sidekiq-unique-jobs'
gem 'slim-rails'
gem 'switch_user'
gem 'view_component', '>= 2.50.0'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: %i[mri mingw x64_mingw]

  ## custom gems
  gem 'annotate', '~> 3.2.0'
  gem 'database_rewinder'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'gimei'
  gem 'guard-rspec', require: false
  gem 'rb-fsevent'
  gem 'rspec-rails'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'timecop'
end

group :development do
  gem 'listen', '~> 3.3'

  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  gem 'rack-mini-profiler', '~> 2.0'

  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'

  ## custom gems
  gem 'bullet'
  gem 'foreman'
  gem 'html2slim'
  gem 'seed_dump'
  gem 'yard'
end

group :development, :staging do
  gem 'letter_opener_web'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 3.26'
  
  gem 'selenium-webdriver'
  
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'

  ## custom gems
  gem 'rails-controller-testing'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
