source 'https://rubygems.org'

ruby '3.2.3'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 7.1.3'

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem 'sprockets-rails'

# Use sqlite3 as the database for Active Record
# gem "sqlite3", "~> 1.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem 'importmap-rails'

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem 'turbo-rails'

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem 'stimulus-rails'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder'

# Use Redis adapter to run Action Cable in production
gem 'redis', '>= 4.0.1'

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password
gem 'bcrypt', '~> 3.1.7'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
gem 'image_processing', '~> 1.2'

# Use postgresql as the database for Active Record
gem 'pg'

# Use Tailwind CSS [https://github.com/rails/tailwindcss-rails]
gem 'tailwindcss-rails'

## custom gems
gem 'action_args'
gem 'active_decorator'
gem 'active_hash'
# TODO: replace this with following moduleralized gems to reduce the gem size
# to do that, we need to investigate how to send emails using aws-sdk-ses with devise_invitable
gem 'aws-sdk-rails'
gem 'aws-sdk-s3'
# gem 'aws-sdk-ses'
gem 'cancancan'
gem 'devise'
gem 'devise_invitable', '~> 2.0.0'
gem 'enum_help'
gem 'html5_validators'
gem 'httparty'
gem 'i18n-tasks'
gem 'inline_svg'
gem 'kaminari'
gem 'lograge'
gem 'lookbook'
gem 'mini_magick'
gem 'net-imap', require: false
gem 'net-pop', require: false
gem 'net-smtp', require: false
gem 'nokogiri'
gem 'okcomputer'
gem 'omniauth'
gem 'omniauth-google-oauth2'
gem 'omniauth-rails_csrf_protection'
gem 'rails-flog'
gem 'rexml'
gem 'rubocop', require: false
gem 'rubocop-rails', require: false
gem 'rubocop-rspec', require: false
gem 'sentry-rails'
gem 'sentry-ruby'
gem 'sidekiq'
gem 'sidekiq-cron'
gem 'sidekiq-unique-jobs'
gem 'switch_user'
gem 'view_component', '>= 2.50.0'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ]

  ## custom gems
  gem 'annotate', '~> 3.2.0'
  gem 'database_rewinder'
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'gimei'
  gem 'guard-rspec', require: false
  gem 'rb-fsevent'
  gem 'rspec-rails'
  gem 'timecop'
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  gem "rack-mini-profiler"
 
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  gem "spring"

  ## custom gems
  gem 'bullet'
  gem 'foreman'
  gem 'htmlbeautifier'
  gem 'seed_dump'
  gem 'spring-commands-rspec'
  gem 'yard'
end

group :development, :staging do
  ## custom gems
  gem 'letter_opener_web'
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem 'capybara'

  ## custom gems
  gem 'cuprite'
  gem 'rails-controller-testing'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
  gem 'simplecov-cobertura'
end
